{% if stack == "python-fastapi" %}
FROM python:3.11

WORKDIR /app
COPY . .

RUN pip install fastapi uvicorn

CMD ["uvicorn", "src.python-fastapi.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
{% endif %}

{% if stack == "node-nest" %}
FROM node:20

WORKDIR /app
COPY . .

RUN npm install

CMD ["npm", "run", "start"]
{% endif %}
