FROM {{ stack == 'python' and 'python:3.12-slim' or stack == 'typescript' and 'node:22-slim' or 'golang:1.23' }}

WORKDIR /app
COPY . .
{% if stack == 'python' -%}
CMD ["python", "src/main.{{ main_extension }}"]
{% elif stack == 'typescript' -%}
CMD ["node", "--experimental-strip-types", "src/main.{{ main_extension }}"]
{% elif stack == 'go' -%}
RUN go build -o /app/bin/main src/main.{{ main_extension }}
CMD ["/app/bin/main"]
{% endif %}
